// ```````````````````````````````````````````````````````````````````````````````````````````````````````
//
//
//
//     Time : Making Portfolio Website
//     Project : Portfolio - Pranav
//     Details : My portfolio website - NextJS & Tailwind CSS
//     Date :
//           Started :           27/8/2023 - Sunday
//           Completed :           28/8/2023 - Monday
//           Development :       28/8/2023 => continue
//
//
//
// ````````````````````````````````````````````````````````````````````````````````````````````````````````

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pranav Shilavane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
